name: aji
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cloud_firestore: ^0.16.0+1
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.12.4
  flutter_svg: ^0.20.0-nullsafety.3
  google_sign_in: "^4.5.1"
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+22
  shared_preferences: ^2.0.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
flutter:
  uses-material-design: true
  assets:
    - images/
